name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
        registry-url: https://npm.pkg.github.com
        scope: '@zbrckovic'
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: npm run build-storybook
    - run: npm run deploy-storybook -- --ci --existing-output-dir=./storybook-static
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

